name: "Basic"
x-type: "hlfv1"
description: "Basic network"
version: "1.0"
channels:
  mychannel:
    orderers:
      - orderer1.example.com

    peers:
      peer0.msb1.example.com:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true

      peer1.msb1.example.com:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true

      peer0.msb2.example.com:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true

      peer1.msb2.example.com:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true

      peer0.msb3.example.com:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true

      peer1.msb3.example.com:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true

    chaincodes:
      - mycc:v0

organizations:
  MSB1:
    mspid: MSB1

    peers:
      - peer0.msb1.example.com
      - peer1.msb2.example.com

    certificateAuthorities:
      - ca.msb1.example.com

    adminPrivateKey:
      path: ../artifacts/channel/crypto-config/peerOrganizations/msb1.example.com/users/Admin@msb1.example.com/msp/keystore/priv_sk
    signedCert:
      path: ../artifacts/channel/crypto-config/peerOrganizations/msb1.example.com/users/Admin@msb1.example.com/msp/signcerts/Admin@msb1.example.com-cert.pem

  MSB2:
    mspid: MSB2

    peers:
      - peer0.msb2.example.com
      - peer1.msb2.example.com

    certificateAuthorities:
      - ca.msb2.example.com

    adminPrivateKey:
      path: ../artifacts/channel/crypto-config/peerOrganizations/msb2.example.com/users/Admin@msb2.example.com/msp/keystore/priv_sk
    signedCert:
      path: ../artifacts/channel/crypto-config/peerOrganizations/msb2.example.com/users/Admin@msb2.example.com/msp/signcerts/Admin@msb2.example.com-cert.pem
  
  MSB3:
    mspid: MSB3

    peers:
      - peer0.msb3.example.com
      - peer1.msb3.example.com

    certificateAuthorities:
      - ca.msb3.example.com

    adminPrivateKey:
      path: ../artifacts/channel/crypto-config/peerOrganizations/msb3.example.com/users/Admin@msb3.example.com/msp/keystore/priv_sk
    signedCert:
      path: ../artifacts/channel/crypto-config/peerOrganizations/msb3.example.com/users/Admin@msb3.example.com/msp/signcerts/Admin@msb3.example.com-cert.pem


orderers:
  orderer1.example.com:
    url: grpcs://localhost:7050
    grpcOptions:
      ssl-target-name-override: orderer1.example.com
    tlsCACerts:
      path: ../artifacts/channel/crypto-config/ordererOrganizations/example.com/orderers/orderer1.example.com/tls/ca.crt

  orderer2.example.com:
    url: grpcs://localhost:8050
    grpcOptions:
      ssl-target-name-override: orderer2.example.com
    tlsCACerts:
      path: ../artifacts/channel/crypto-config/ordererOrganizations/example.com/orderers/orderer2.example.com/tls/ca.crt

  orderer3.example.com:
    url: grpcs://localhost:9050
    grpcOptions:
      ssl-target-name-override: orderer3.example.com
    tlsCACerts:
      path: ../artifacts/channel/crypto-config/ordererOrganizations/example.com/orderers/orderer3.example.com/tls/ca.crt

#
# List of peers to send various requests to, including endorsement, query
# and event listener registration.
#
peers:
  peer0.msb1.example.com:
    url: grpcs://localhost:7051

    grpcOptions:
      ssl-target-name-override: peer0.msb1.example.com
    tlsCACerts:
      path: ../artifacts/channel/crypto-config/peerOrganizations/msb1.example.com/peers/peer0.msb1.example.com/tls/ca.crt

  peer1.msb1.example.com:
    url: grpcs://localhost:8051

    grpcOptions:
      ssl-target-name-override: peer1.msb1.example.com
    tlsCACerts:
      path: ../artifacts/channel/crypto-config/peerOrganizations/msb1.example.com/peers/peer1.msb1.example.com/tls/ca.crt

  peer0.msb2.example.com:
    url: grpcs://localhost:9051

    grpcOptions:
      ssl-target-name-override: peer0.msb2.example.com
    tlsCACerts:
      path: ../artifacts/channel/crypto-config/peerOrganizations/msb2.example.com/peers/peer0.msb2.example.com/tls/ca.crt

  peer1.msb2.example.com:
    url: grpcs://localhost:10051

    grpcOptions:
      ssl-target-name-override: peer1.msb2.example.com
    tlsCACerts:
      path: ../artifacts/channel/crypto-config/peerOrganizations/msb2.example.com/peers/peer1.msb2.example.com/tls/ca.crt
  
  
  peer0.msb3.example.com:
    url: grpcs://localhost:9051

    grpcOptions:
      ssl-target-name-override: peer0.msb3.example.com
    tlsCACerts:
      path: ../artifacts/channel/crypto-config/peerOrganizations/msb3.example.com/peers/peer0.msb3.example.com/tls/ca.crt

  peer1.msb3.example.com:
    url: grpcs://localhost:10051

    grpcOptions:
      ssl-target-name-override: peer1.msb3.example.com
    tlsCACerts:
      path: ../artifacts/channel/crypto-config/peerOrganizations/msb3.example.com/peers/peer1.msb3.example.com/tls/ca.crt


#
# Fabric-CA is a special kind of Certificate Authority provided by Hyperledger Fabric which allows
# certificate management to be done via REST APIs. Application may choose to use a standard
# Certificate Authority instead of Fabric-CA, in which case this section would not be specified.
#
certificateAuthorities:
  ca.msb1.example.com:
    url: https://localhost:7054
    httpOptions:
      verify: false
    tlsCACerts:
      path: ../artifacts/channel/crypto-config/peerOrganizations/msb1.example.com/ca/ca.msb1.example.com-cert.pem

    registrar:
      - enrollId: admin
        enrollSecret: adminpw
    caName: ca.msb1.example.com

  ca.msb2.example.com:
    url: https://localhost:8054
    httpOptions:
      verify: false
    tlsCACerts:
      path: ../artifacts/channel/crypto-config/peerOrganizations/msb2.example.com/ca/ca.msb2.example.com-cert.pem

    registrar:
      - enrollId: admin
        enrollSecret: adminpw
    caName: ca.msb2.example.com


  ca.msb3.example.com:
    url: https://localhost:9054
    httpOptions:
      verify: false
    tlsCACerts:
      path: ../artifacts/channel/crypto-config/peerOrganizations/msb3.example.com/ca/ca.msb3.example.com-cert.pem

    registrar:
      - enrollId: admin
        enrollSecret: adminpw
    caName: ca.msb3.example.com
