# This file generates crypto materials

# ---------------------------------------------------------------------------
# "OrdererOrgs" - Definition of organizations managing orderer nodes
# ---------------------------------------------------------------------------
OrdererOrgs:
  # ---------------------------------------------------------------------------
  # Orderer
  # ---------------------------------------------------------------------------
  - Name: Orderer #the name of the orgs that host the ordered nodes
    Domain: example.com
    Specs:
      - Hostname: orderer
# ---------------------------------------------------------------------------
# "PeerOrgs" - Definition of organizations managing peer nodes
# ---------------------------------------------------------------------------
PeerOrgs:
  - Name: MSB1
    Domain: msb1.example.com
    Template:
      Count: 1
    Users:
      Count: 1
  - Name: MSB2
    Domain: msb2.example.com
    Template:
      Count: 1
    Users:
      Count: 1
  - Name: MSB3
    Domain: org3.example.com
    Template:
      Count: 1
    Users:
      Count: 1